@echo off
REM Bootstraps ads-deploy on a Windows TwinCAT XAE machine:
REM   1. Verify uv, pixi, and git are installed.
REM   2. Install ads-deploy and pre-commit as uv tools (global shims, no
REM      activation needed to run them). By default this is a PER-USER
REM      install (uv's own default); set ADS_DEPLOY_SHARED_DIR first for a
REM      shared, all-users install instead -- see the comment further down.
REM      Also installs the pathmunge-activate helper scripts alongside them,
REM      for ad hoc CLI use of pinned tools outside of TwinCAT/VS.
REM   3. Install the pinned pytmc and make versions, each into their own
REM      isolated pixi environment (pytmc from PyPI, make from conda-forge
REM      -- see ads_deploy/tool_registry.py).
REM   4. Fetch ads-ioc (its latest version is auto-discovered at build time
REM      by `ads-deploy build`, no cached location file needed).
REM   5. Regenerate external-tools.vssettings. Command is ads-deploy's own
REM      resolved path (Visual Studio's External Tools does NOT do a PATH
REM      search the way cmd.exe does -- confirmed directly, a bare
REM      "ads-deploy" is rejected as "not a valid executable"), so this file
REM      must be regenerated on each machine it's generated FROM. It does
REM      NOT need to be regenerated by each machine/user it's IMPORTED on,
REM      though: importing a .vssettings file copies its contents into
REM      Visual Studio's own per-user settings store, so in shared-install
REM      mode this one generated file can be handed to every other user on
REM      the machine to import as-is -- see the comment further down.
REM
REM Every step below checks ERRORLEVEL and stops the script on failure --
REM a failed step must never be silently followed by later steps.

where uv >nul 2>nul
IF %ERRORLEVEL% NEQ 0 (
    echo uv was not found on PATH.
    echo Install it first: https://docs.astral.sh/uv/getting-started/installation/
    EXIT /B 1
)

where pixi >nul 2>nul
IF %ERRORLEVEL% NEQ 0 (
    echo pixi was not found on PATH ^(ads-deploy install needs it to
    echo provision tools from PyPI and conda-forge^).
    echo Install it first: https://pixi.sh/latest/installation/
    EXIT /B 1
)

REM Git for Windows provides both `git` (needed to fetch ads-ioc) and the
REM `sh.exe`/`bash.exe` that GNU Make's Windows port looks for to run
REM Makefile recipes -- ads-deploy's own code no longer invokes bash for
REM orchestration (see DESIGN.md), but make's own recipe execution can still
REM depend on it, so Git for Windows stays a prerequisite either way.
where git >nul 2>nul
IF %ERRORLEVEL% NEQ 0 (
    echo git was not found on PATH ^(needed to fetch ads-ioc, and make's own
    echo recipe execution typically needs the sh.exe Git for Windows provides^).
    echo Install Git for Windows: https://git-scm.com/download/win
    EXIT /B 1
)

REM %~dp0 always ends in a backslash; a trailing backslash right before a
REM closing quote escapes the quote on Windows, so strip it before quoting.
SET "RepoRoot=%~dp0"
SET "RepoRoot=%RepoRoot:~0,-1%"

REM Optional: install ads-deploy (and the pinned pytmc/make/pre-commit) to a
REM SHARED location instead of the current user's own profile, so every
REM other user on this machine can just IMPORT the vssettings file this
REM script generates at the end -- no install command of their own, ever.
REM To use this mode, set ADS_DEPLOY_SHARED_DIR to a shared path before
REM running bootstrap.cmd, e.g.:
REM     set ADS_DEPLOY_SHARED_DIR=C:\ProgramData\ads-deploy
REM Leave it unset for the default, per-user install -- `uv tool install`'s
REM own default, which is NOT visible to other users on the machine.
REM
REM Pick a location under C:\ProgramData (not e.g. C:\Repos\...): its
REM default ACLs give ordinary users read+execute but not write, which is
REM what keeps a curious/novice user from corrupting the shared install --
REM confirmed via `icacls`. This script does not set permissions itself; it
REM relies on that default.
REM
REM This only sets UV_TOOL_DIR/UV_TOOL_BIN_DIR for THIS SCRIPT's own run
REM (safe, standalone values, not persisted via setx -- a future admin
REM re-run just sets them again the same way; there's nothing durable worth
REM persisting here). It deliberately never touches the system PATH itself:
REM `setx /M PATH ...` has a hard 1024-character limit and silently
REM TRUNCATES longer values, which can corrupt the whole machine's PATH --
REM too risky to do unattended from a script, especially since the VS
REM External Tools workflow doesn't need PATH at all (see the vssettings
REM step below) -- extending PATH machine-wide is now optional, only for
REM people who also want `ads-deploy`/`pytmc`/`make`/`pre-commit` from a
REM plain terminal. Computed here, OUTSIDE any block: a variable SET inside
REM a parenthesized ( ... ) block and then read later in that SAME block
REM expands to empty (cmd.exe freezes %VAR% substitutions to their
REM pre-block value for the whole block) -- confirmed directly, caught via
REM testing, same gotcha fixed elsewhere in this project's .cmd files.
IF NOT "%ADS_DEPLOY_SHARED_DIR%"=="" (
    SET "UV_TOOL_DIR=%ADS_DEPLOY_SHARED_DIR%\uv-tools"
    SET "UV_TOOL_BIN_DIR=%ADS_DEPLOY_SHARED_DIR%\bin"
    REM UV_TOOL_DIR/UV_TOOL_BIN_DIR only affect `uv tool install` (ads-deploy,
    REM pre-commit themselves) -- only THIS script's own run needs them, so a
    REM plain session-local SET is enough (see the long comment above).
    REM
    REM ADS_DEPLOY_TOOLENV_ROOT is different: it redirects the per-(tool,
    REM version) pixi environments `ads-deploy install` creates for
    REM pytmc/make (ads_deploy/toolenv.py's toolenv_root(), per-user AppData
    REM by default). Unlike the vssettings Command path, OTHER users' later
    REM `ads-deploy build`/`lint`/etc. calls (spawned fresh by Visual Studio,
    REM with none of this script's session state) also need to see this
    REM variable -- so it must be set SYSTEM-WIDE, not just for this run.
    REM setx is safe to use here (unlike for PATH): it's one short, standalone
    REM string, nowhere near setx's 1024-character truncation limit.
    SET "ADS_DEPLOY_TOOLENV_ROOT=%ADS_DEPLOY_SHARED_DIR%\toolenvs"
    echo Installing to the shared location %ADS_DEPLOY_SHARED_DIR% ...
    setx /M ADS_DEPLOY_TOOLENV_ROOT "%ADS_DEPLOY_TOOLENV_ROOT%" >nul
    REM `IF %ERRORLEVEL% NEQ 0` would NOT work here: this whole IF is nested
    REM inside the outer ADS_DEPLOY_SHARED_DIR block, and cmd.exe pre-expands
    REM every %VAR% in a parenthesized block once, at the moment the block is
    REM ENTERED -- so %ERRORLEVEL% here would stay frozen at its pre-setx
    REM value (0) no matter what setx actually returns, silently masking a
    REM real failure (confirmed directly: this exact bug shipped and hid a
    REM genuine "run as Administrator" failure). `IF ERRORLEVEL 1` is a
    REM special conditional form, not a %...% substitution -- cmd.exe
    REM evaluates it live, immune to the freezing.
    IF ERRORLEVEL 1 (
        echo ** FAILED: could not set ADS_DEPLOY_TOOLENV_ROOT system-wide. Run this script as Administrator. **
        EXIT /B 1
    )
)

IF "%PYTMC_VERSION%"=="" (
    echo Set PYTMC_VERSION to the pytmc version you want to pin, e.g.:
    echo     cmd.exe:     set PYTMC_VERSION=v2.22.2 ^&^& bootstrap.cmd
    echo     PowerShell:  $env:PYTMC_VERSION = "v2.22.2"; .\bootstrap.cmd
    EXIT /B 1
)

IF "%MAKE_VERSION%"=="" (
    echo Set MAKE_VERSION to the GNU Make version to pin ^(from conda-forge^),
    echo e.g. 4.4.1:
    echo     cmd.exe:     set MAKE_VERSION=4.4.1 ^&^& bootstrap.cmd
    echo     PowerShell:  $env:MAKE_VERSION = "4.4.1"; .\bootstrap.cmd
    EXIT /B 1
)

echo Installing ads-deploy as a uv tool from %RepoRoot% ...
uv tool install --force "%RepoRoot%"
IF %ERRORLEVEL% NEQ 0 (
    echo ** FAILED: could not install ads-deploy. **
    EXIT /B 1
)

REM Drop the pathmunge-activate helper scripts next to the ads-deploy shim
REM itself (uv's own tool-shim bin dir, already on PATH) so they're
REM immediately callable from any shell with no extra PATH setup. These
REM exist for ad hoc CLI use outside of TwinCAT/VS -- `ads-deploy pathmunge`
REM alone can only ever PRINT the resolved PATH fragment (a plain .exe can
REM never modify its parent shell's environment), so these wrap the same
REM capture-and-prepend config.cmd already does, for direct interactive use.
FOR /F "usebackq delims=" %%B in (`uv tool dir --bin`) DO SET "UvToolBin=%%B"
copy /Y "%RepoRoot%\ads_deploy\windows\pathmunge-activate.cmd" "%UvToolBin%\pathmunge-activate.cmd" >nul
copy /Y "%RepoRoot%\ads_deploy\windows\pathmunge-activate.ps1" "%UvToolBin%\pathmunge-activate.ps1" >nul
IF %ERRORLEVEL% NEQ 0 (
    echo ** FAILED: could not install pathmunge-activate helper scripts. **
    EXIT /B 1
)

REM `uv tool install` only persists PATH for FUTURE sessions (it registers
REM its bin dir via the user/machine PATH, not this already-running one) --
REM so this script's own later bare `ads-deploy ...` calls below need this
REM session-local prepend to resolve right now, regardless of whether this
REM is a shared or per-user install. Plain SET, not setx -- no truncation
REM risk, and nothing durable is being changed here.
SET "PATH=%UvToolBin%;%PATH%"

echo.
echo Installing pre-commit as a uv tool ...
uv tool install --force pre-commit
IF %ERRORLEVEL% NEQ 0 (
    echo ** FAILED: could not install pre-commit. **
    EXIT /B 1
)

echo.
echo Installing pytmc %PYTMC_VERSION% into its own isolated environment ...
ads-deploy install pytmc/%PYTMC_VERSION%
IF %ERRORLEVEL% NEQ 0 (
    echo ** FAILED: could not install pytmc/%PYTMC_VERSION%. **
    echo Check that this is a real pytmc release tag/version.
    EXIT /B 1
)

echo.
echo Installing make %MAKE_VERSION% into its own isolated environment ...
ads-deploy install make/%MAKE_VERSION%
IF %ERRORLEVEL% NEQ 0 (
    echo ** FAILED: could not install make/%MAKE_VERSION%. **
    echo Check that this is a real conda-forge make version.
    EXIT /B 1
)

echo.
echo Fetching ads-ioc ...
ads-deploy fetch-ads-ioc
IF %ERRORLEVEL% NEQ 0 (
    echo ** FAILED: could not fetch ads-ioc. **
    EXIT /B 1
)

echo.
echo Regenerating external-tools.vssettings ...
ads-deploy vssettings --output "%RepoRoot%\external-tools.vssettings"
IF %ERRORLEVEL% NEQ 0 (
    echo ** FAILED: could not regenerate external-tools.vssettings. **
    EXIT /B 1
)

echo.
echo Done. Import external-tools.vssettings into Visual Studio
echo (Tools ^> Import and Export Settings...).
IF NOT "%ADS_DEPLOY_SHARED_DIR%"=="" (
    echo.
    echo Shared install complete. Hand the generated
    echo %RepoRoot%\external-tools.vssettings to every other user on this
    echo machine to import as-is -- they do not need to run this script, or
    echo any command, themselves.
    echo.
    echo NOTE: ADS_DEPLOY_TOOLENV_ROOT was just set SYSTEM-WIDE so other
    echo users' VS-launched `ads-deploy build`/`lint`/etc. calls can find the
    echo shared pytmc/make environments. Like any system environment
    echo variable change, this only takes effect for OTHER users the next
    echo time they log in ^(not retroactively for an already-open session^)
    echo -- standard Windows behavior, nothing this script can do about it.
    echo.
    echo Optional: if people also want `ads-deploy`/`pytmc`/`make`/
    echo `pre-commit` available from a plain terminal ^(not needed for the
    echo VS External Tools workflow above^), add %UV_TOOL_BIN_DIR% to the
    echo SYSTEM PATH once, as Administrator, in PowerShell:
    echo     [Environment]::SetEnvironmentVariable^('Path', [Environment]::GetEnvironmentVariable^('Path','Machine'^) + ';%UV_TOOL_BIN_DIR%', 'Machine'^)
)
