@echo off
REM Bootstraps ads-deploy on a Windows TwinCAT XAE machine:
REM   1. Verify uv, pixi, and git are installed.
REM   2. Install ads-deploy and pre-commit as uv tools (global shims, no
REM      activation needed to run them). By default this is a PER-USER
REM      install (uv's own default); set ADS_DEPLOY_SHARED_DIR first for a
REM      shared, all-users install instead -- see the comment further down.
REM      Also installs the pathmunge-activate helper scripts alongside them,
REM      for ad hoc CLI use of pinned tools outside of TwinCAT/VS.
REM   3. Install the pinned pytmc and make versions, each into their own
REM      isolated pixi environment (pytmc from PyPI, make from conda-forge
REM      -- see ads_deploy/tool_registry.py).
REM   4. Fetch ads-ioc (its latest version is auto-discovered at build time
REM      by `ads-deploy build`, no cached location file needed).
REM   5. Regenerate external-tools.vssettings. Command is ads-deploy's own
REM      resolved path (Visual Studio's External Tools does NOT do a PATH
REM      search the way cmd.exe does -- confirmed directly, a bare
REM      "ads-deploy" is rejected as "not a valid executable"), so this file
REM      must be regenerated on each machine it's generated FROM. It does
REM      NOT need to be regenerated by each machine/user it's IMPORTED on,
REM      though: importing a .vssettings file copies its contents into
REM      Visual Studio's own per-user settings store, so in shared-install
REM      mode this one generated file can be handed to every other user on
REM      the machine to import as-is -- see the comment further down.
REM
REM Every step below checks ERRORLEVEL and stops the script on failure --
REM a failed step must never be silently followed by later steps.

where uv >nul 2>nul
IF %ERRORLEVEL% NEQ 0 (
    echo uv was not found on PATH.
    echo Install it first: https://docs.astral.sh/uv/getting-started/installation/
    EXIT /B 1
)

where pixi >nul 2>nul
IF %ERRORLEVEL% NEQ 0 (
    echo pixi was not found on PATH ^(ads-deploy install needs it to
    echo provision tools from PyPI and conda-forge^).
    echo Install it first: https://pixi.sh/latest/installation/
    EXIT /B 1
)

REM Git for Windows provides both `git` (needed to fetch ads-ioc) and the
REM `sh.exe`/`bash.exe` that GNU Make's Windows port looks for to run
REM Makefile recipes -- ads-deploy's own code no longer invokes bash for
REM orchestration (see DESIGN.md), but make's own recipe execution can still
REM depend on it, so Git for Windows stays a prerequisite either way.
where git >nul 2>nul
IF %ERRORLEVEL% NEQ 0 (
    echo git was not found on PATH ^(needed to fetch ads-ioc, and make's own
    echo recipe execution typically needs the sh.exe Git for Windows provides^).
    echo Install Git for Windows: https://git-scm.com/download/win
    EXIT /B 1
)

REM %~dp0 always ends in a backslash; a trailing backslash right before a
REM closing quote escapes the quote on Windows, so strip it before quoting.
SET "RepoRoot=%~dp0"
SET "RepoRoot=%RepoRoot:~0,-1%"

REM Optional: install ads-deploy (and the pinned pytmc/make/pre-commit) to a
REM SHARED location instead of the current user's own profile, so every
REM other user on this machine can just IMPORT the vssettings file this
REM script generates at the end -- no install command of their own, ever,
REM and (as of this version) no registry/env-var step for anyone either.
REM To use this mode, set ADS_DEPLOY_SHARED_DIR before running bootstrap.cmd:
REM     set ADS_DEPLOY_SHARED_DIR=C:\ProgramData\ads-deploy
REM Leave it unset for the default, per-user install -- `uv tool install`'s
REM own default, which is NOT visible to other users on the machine.
REM
REM Use EXACTLY this path, not a different one: two separate things depend
REM on it being C:\ProgramData\ads-deploy specifically.
REM   1. C:\ProgramData's default ACLs give ordinary users read+execute but
REM      not write, which is what keeps a curious/novice user from
REM      corrupting the shared install -- confirmed via `icacls`. This
REM      script does not set permissions itself; it relies on that default,
REM      which a different, user-writable location (e.g. C:\Repos\...)
REM      would not give you.
REM   2. `ads_deploy/toolenv.py`'s toolenv_root() auto-detects the pixi
REM      toolenvs directory specifically at %ProgramData%\ads-deploy\toolenvs
REM      and uses it automatically if it exists -- no env var, no setx, no
REM      admin rights needed by any other user. This is why the setx /M
REM      ADS_DEPLOY_TOOLENV_ROOT step this script used to have is gone: it's
REM      no longer needed at all when this convention is followed. A
REM      different ADS_DEPLOY_SHARED_DIR still works (via an explicit
REM      ADS_DEPLOY_TOOLENV_ROOT override), but loses this auto-detection,
REM      and would need every other user to set that override themselves.
REM
REM UV_PYTHON_INSTALL_DIR is redirected here too, not just UV_TOOL_DIR/
REM UV_TOOL_BIN_DIR: uv's own managed Python interpreters otherwise install
REM to the CURRENT user's profile (%APPDATA%\uv\python) regardless of
REM UV_TOOL_DIR, so the shared tool venv would reference an interpreter
REM path under the admin's own AppData -- inaccessible to every other user
REM (confirmed directly: `Access is denied` reaching into another user's
REM profile). Redirecting this alongside the others keeps the interpreter
REM itself under the ACL-protected shared install too.
REM
REM UV_LINK_MODE=copy is also forced here: uv's default install strategy is
REM to HARDLINK installed package files back to its own global cache
REM (normally under the invoking user's profile) rather than copy them, to
REM save disk space. A hardlink shares its underlying file's NTFS security
REM descriptor with the original -- so even though the destination
REM directory sits under ProgramData's own permissive ACL, individual
REM package files inside it stayed gated by the admin's own profile ACL
REM (confirmed directly: other users could launch ads-deploy.exe itself,
REM but every subcommand failed importing its dependencies with
REM "Access is denied" / PermissionError reaching into
REM C:\Users\<admin>\...\uv\cache\...). Forcing a real copy during a shared
REM install makes every installed file's permissions inherit from
REM ProgramData directly, independent of the cache.
REM
REM PIXI_NO_HARD_LINKS=1 forces the same real-copy behavior for the
REM pytmc/make toolenvs pixi provisions below -- pixi hard-links package
REM files from its own cache (PIXI_CACHE_DIR, default under the invoking
REM user's profile) into each environment for the identical reason uv
REM does, and hits the identical cross-user permission problem.
REM
REM This only sets UV_TOOL_DIR/UV_TOOL_BIN_DIR/UV_PYTHON_INSTALL_DIR/
REM UV_LINK_MODE/PIXI_NO_HARD_LINKS/ADS_DEPLOY_TOOLENV_ROOT for
REM THIS SCRIPT's own run (safe, standalone values, nothing persisted -- a
REM future admin re-run just sets them again the same way). This script
REM deliberately never touches the system PATH itself: `setx /M PATH ...`
REM has a hard 1024-character limit and silently TRUNCATES longer values,
REM which can corrupt the whole machine's PATH -- too risky to do
REM unattended from a script, especially since the VS External Tools
REM workflow doesn't need PATH at all (see the vssettings step below) --
REM extending PATH machine-wide is optional, only for people who also want
REM `ads-deploy`/`pytmc`/`make`/`pre-commit` from a plain terminal. Computed
REM here, OUTSIDE any block: a variable SET inside a parenthesized ( ... )
REM block and then read later in that SAME block expands to empty (cmd.exe
REM freezes %VAR% substitutions to their pre-block value for the whole
REM block) -- confirmed directly, caught via testing, same gotcha fixed
REM elsewhere in this project's .cmd files.
IF NOT "%ADS_DEPLOY_SHARED_DIR%"=="" (
    SET "UV_TOOL_DIR=%ADS_DEPLOY_SHARED_DIR%\uv-tools"
    SET "UV_TOOL_BIN_DIR=%ADS_DEPLOY_SHARED_DIR%\bin"
    SET "UV_PYTHON_INSTALL_DIR=%ADS_DEPLOY_SHARED_DIR%\uv-python"
    SET "UV_LINK_MODE=copy"
    SET "PIXI_NO_HARD_LINKS=1"
    SET "ADS_DEPLOY_TOOLENV_ROOT=%ADS_DEPLOY_SHARED_DIR%\toolenvs"
    echo Installing to the shared location %ADS_DEPLOY_SHARED_DIR% ...
)

REM PYTMC_VERSION/MAKE_VERSION are OPTIONAL: set them to pin an exact
REM version (recommended for any real deployment -- see README's note on
REM pixi.lock strictness), e.g.:
REM     cmd.exe:     set PYTMC_VERSION=v2.22.2 ^&^& set MAKE_VERSION=4.4.1 ^&^& bootstrap.cmd
REM     PowerShell:  $env:PYTMC_VERSION = "v2.22.2"; $env:MAKE_VERSION = "4.4.1"; .\bootstrap.cmd
REM Leave either unset to install whatever's latest upstream right now --
REM a convenience for getting started, not a substitute for pinning.
REM Computed here, OUTSIDE any block -- see the cmd.exe block-freezing
REM gotcha explained at length further up this file.
SET "PytmcSpec=pytmc"
IF NOT "%PYTMC_VERSION%"=="" SET "PytmcSpec=pytmc/%PYTMC_VERSION%"
SET "MakeSpec=make"
IF NOT "%MAKE_VERSION%"=="" SET "MakeSpec=make/%MAKE_VERSION%"

echo Installing ads-deploy as a uv tool from %RepoRoot% ...
uv tool install --force "%RepoRoot%"
IF %ERRORLEVEL% NEQ 0 (
    echo ** FAILED: could not install ads-deploy. **
    EXIT /B 1
)

REM Drop the pathmunge-activate helper scripts next to the ads-deploy shim
REM itself (uv's own tool-shim bin dir, already on PATH) so they're
REM immediately callable from any shell with no extra PATH setup. These
REM exist for ad hoc CLI use outside of TwinCAT/VS -- `ads-deploy pathmunge`
REM alone can only ever PRINT the resolved PATH fragment (a plain .exe can
REM never modify its parent shell's environment), so these wrap the same
REM capture-and-prepend config.cmd already does, for direct interactive use.
FOR /F "usebackq delims=" %%B in (`uv tool dir --bin`) DO SET "UvToolBin=%%B"
copy /Y "%RepoRoot%\ads_deploy\windows\pathmunge-activate.cmd" "%UvToolBin%\pathmunge-activate.cmd" >nul
copy /Y "%RepoRoot%\ads_deploy\windows\pathmunge-activate.ps1" "%UvToolBin%\pathmunge-activate.ps1" >nul
IF %ERRORLEVEL% NEQ 0 (
    echo ** FAILED: could not install pathmunge-activate helper scripts. **
    EXIT /B 1
)

REM `uv tool install` only persists PATH for FUTURE sessions (it registers
REM its bin dir via the user/machine PATH, not this already-running one) --
REM so this script's own later bare `ads-deploy ...` calls below need this
REM session-local prepend to resolve right now, regardless of whether this
REM is a shared or per-user install. Plain SET, not setx -- no truncation
REM risk, and nothing durable is being changed here.
SET "PATH=%UvToolBin%;%PATH%"

echo.
echo Installing pre-commit as a uv tool ...
uv tool install --force pre-commit
IF %ERRORLEVEL% NEQ 0 (
    echo ** FAILED: could not install pre-commit. **
    EXIT /B 1
)

echo.
echo Installing %PytmcSpec% into its own isolated environment ...
ads-deploy install %PytmcSpec%
IF %ERRORLEVEL% NEQ 0 (
    echo ** FAILED: could not install %PytmcSpec%. **
    echo Check that this is a real pytmc release tag/version.
    EXIT /B 1
)

echo.
echo Installing %MakeSpec% into its own isolated environment ...
ads-deploy install %MakeSpec%
IF %ERRORLEVEL% NEQ 0 (
    echo ** FAILED: could not install %MakeSpec%. **
    echo Check that this is a real conda-forge make version.
    EXIT /B 1
)

echo.
echo Fetching ads-ioc ...
ads-deploy fetch-ads-ioc
IF %ERRORLEVEL% NEQ 0 (
    echo ** FAILED: could not fetch ads-ioc. **
    EXIT /B 1
)

echo.
echo Regenerating external-tools.vssettings ...
ads-deploy vssettings --output "%RepoRoot%\external-tools.vssettings"
IF %ERRORLEVEL% NEQ 0 (
    echo ** FAILED: could not regenerate external-tools.vssettings. **
    EXIT /B 1
)

echo.
echo Done. Import external-tools.vssettings into Visual Studio
echo (Tools ^> Import and Export Settings...).
IF NOT "%ADS_DEPLOY_SHARED_DIR%"=="" (
    echo.
    echo Shared install complete. Hand the generated
    echo %RepoRoot%\external-tools.vssettings to every other user on this
    echo machine to import as-is -- they do not need to run this script, or
    echo any command, themselves.
    echo.
    echo NOTE: other users' VS-launched `ads-deploy build`/`lint`/etc. calls
    echo will automatically find the shared pytmc/make environments at
    echo %ADS_DEPLOY_SHARED_DIR%\toolenvs -- no env var or admin step needed
    echo on their end, as long as ADS_DEPLOY_SHARED_DIR stayed
    echo C:\ProgramData\ads-deploy ^(see bootstrap.cmd's own comments if you
    echo used a different location^).
    echo.
    echo Optional: if people also want `ads-deploy`/`pytmc`/`make`/
    echo `pre-commit` available from a plain terminal ^(not needed for the
    echo VS External Tools workflow above^), add %UV_TOOL_BIN_DIR% to the
    echo SYSTEM PATH once, as Administrator, in PowerShell:
    echo     [Environment]::SetEnvironmentVariable^('Path', [Environment]::GetEnvironmentVariable^('Path','Machine'^) + ';%UV_TOOL_BIN_DIR%', 'Machine'^)
)
